# Generated by Django 5.1.1 on 2024-09-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cric_profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contry', models.CharField(max_length=100)),
                ('about', models.TextField()),
            ],
        ),
    ]
