# Generated by Django 5.1.1 on 2024-09-24 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cric_buzz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cric_board',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('board_name', models.CharField(max_length=100)),
                ('board_orgin', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='cric_teamInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=200)),
                ('team_nameShortForm', models.CharField(max_length=200)),
                ('team_type', models.CharField(max_length=100)),
                ('team_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taem_borad', to='cric_buzz.cric_board')),
            ],
        ),
        migrations.CreateModel(
            name='cric_series',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('series_name', models.CharField(max_length=200)),
                ('series_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_team', to='cric_buzz.cric_board')),
                ('participate_team', models.ManyToManyField(related_name='host_team', to='cric_buzz.cric_teaminfo')),
            ],
        ),
    ]
